In [1]:
import numpy as np 
import matplotlib.pyplot as plt 
import pandas as pd 
import seaborn as sns 

from univariate_analysis import histogram_by_class, boxplot_by_class

In [2]:
%load_ext autoreload
%autoreload 2

# `POS_CASH_BALANCE.csv` Analysis

In [10]:
from column_analysis import basic_data_summary, TypeTable, MissingValueTable, NumericalSummaryTable, CategoricalSummaryTable

pos_df = pd.read_csv("home_credit/POS_CASH_balance.csv")

In [11]:

basic_data_summary(pos_df)

# Type table 
print("\n" + "=" * 100)
print("1. VARIABLE TYPES")
print("=" * 100)
type_table = TypeTable()
print(type_table.plot_table(pos_df).to_string())


# Missing table
print("\n" + "=" * 100)
print("2. MISSING VALUE ANALYSIS")
print("=" * 100)
missing_table = MissingValueTable()
print(missing_table.plot_table(pos_df).to_string())

print("\n" + "=" * 100)
print("3a. NUMERICAL SUMMARY")
print("=" * 100)
numerical_table = NumericalSummaryTable()
print(numerical_table.plot_table(pos_df).to_string())

print("\n" + "=" * 100)
print("3b. CATEGORICAL SUMMARY")
print("=" * 100)
cat_table = CategoricalSummaryTable()
print(cat_table.plot_table(pos_df).to_string())

Shape: 10,001,358 rows x 8 columns
Memory: 1060.9 MB
Fully duplicated rows: 0

====================================================================================================
1. VARIABLE TYPES
====================================================================================================
                         dtype       inferred_type  n_unique  unique_ratio  example  memory_mb
column
SK_ID_PREV               int64  numeric (discrete)    936325        0.0936  1803195      76.30
SK_ID_CURR               int64  numeric (discrete)    337252        0.0337   182943      76.30
MONTHS_BALANCE           int64  numeric (discrete)        96        0.0000      -31      76.30
CNT_INSTALMENT         float64  numeric (discrete)        73        0.0000     48.0      76.30
CNT_INSTALMENT_FUTURE  float64  numeric (discrete)        79        0.0000     45.0      76.30
NAME_CONTRACT_STATUS       str         categorical         9        0.0000   Active     526.82
SK_DPD                   int64  numeric (discrete)      3400        0.0003        0      76.30
SK_DPD_DEF               int64  numeric (discrete)      2307        0.0002        0      76.30

====================================================================================================
2. MISSING VALUE ANALYSIS
====================================================================================================
                       n_missing  pct_missing  n_native_nan  n_placeholder  n_present  complete
column
CNT_INSTALMENT             26071         0.26         26071              0    9975287     False
CNT_INSTALMENT_FUTURE      26087         0.26         26087              0    9975271     False
SK_ID_CURR                     0         0.00             0              0   10001358      True
SK_ID_PREV                     0         0.00             0              0   10001358      True
MONTHS_BALANCE                 0         0.00             0              0   10001358      True
NAME_CONTRACT_STATUS           0         0.00             0              0   10001358      True
SK_DPD                         0         0.00             0              0   10001358      True
SK_DPD_DEF                     0         0.00             0              0   10001358      True

====================================================================================================
3a. NUMERICAL SUMMARY
====================================================================================================
                            count          mean            std        min        25%        50%        75%        max
column
SK_ID_PREV             10001358.0  1.903217e+06  535846.530722  1000001.0  1434405.0  1896565.0  2368963.0  2843499.0
SK_ID_CURR             10001358.0  2.784039e+05  102763.745090   100001.0   189550.0   278654.0   367429.0   456255.0
MONTHS_BALANCE         10001358.0 -3.501259e+01      26.066570      -96.0      -54.0      -28.0      -13.0       -1.0
CNT_INSTALMENT          9975287.0  1.708965e+01      11.995056        1.0       10.0       12.0       24.0       92.0
CNT_INSTALMENT_FUTURE   9975271.0  1.048384e+01      11.109058        0.0        3.0        7.0       14.0       85.0
SK_DPD                 10001358.0  1.160693e+01     132.714043        0.0        0.0        0.0        0.0     4231.0
SK_DPD_DEF             10001358.0  6.544684e-01      32.762491        0.0        0.0        0.0        0.0     3595.0

====================================================================================================
3b. CATEGORICAL SUMMARY
====================================================================================================
                         count  n_unique   top_1      top_2   top_3   top_4                  top_5
column
NAME_CONTRACT_STATUS  10001358         9  Active  Completed  Signed  Demand  Returned to the store

After reading more detail about this dataset in both the columns description and on the Kaggle website, we understand this dataset to combining all loans a previous customer may have had with home_credit.


__Crucially__, we will isolate only the regular cash loans that a customer previously have had with home_credit, to avoid multicollinearity issues with overlapping information from the credit card information.

In [12]:
credit_df = pd.read_csv("home_credit/credit_card_balance.csv")

# Any SK_ID_PREV appearing in credit_card_balance.csv is a credit card loan -
# drop those rows from pos_df entirely so what remains is cash/POS loans only,
# free of credit-card-specific behaviour.
pos_non_cc = pos_df[~pos_df["SK_ID_PREV"].isin(credit_df["SK_ID_PREV"])]

print(f"pos_df rows before: {len(pos_df):,}")
print(f"pos_df rows after removing credit-card-overlap SK_ID_PREV: {len(pos_non_cc):,}")
print(f"rows removed: {len(pos_df) - len(pos_non_cc):,} "
      f"({100 * (len(pos_df) - len(pos_non_cc)) / len(pos_df):.2f}%)")

pos_non_cc.head()

pos_df rows before: 10,001,358
pos_df rows after removing credit-card-overlap SK_ID_PREV: 10,001,358
rows removed: 0 (0.00%)

   SK_ID_PREV  SK_ID_CURR  ...  SK_DPD  SK_DPD_DEF
0     1803195      182943  ...       0           0
1     1715348      367990  ...       0           0
2     1784872      397406  ...       0           0
3     1903291      269225  ...       0           0
4     2341044      334279  ...       0           0

[5 rows x 8 columns]

Zero rows removed - `SK_ID_PREV` never overlaps between `POS_CASH_balance.csv`
and `credit_card_balance.csv` at all, even though their numeric ranges look
similar (~1,000,000-2,843,500 in both). `SK_ID_PREV` identifies one specific
previous application/product, not a customer, so a customer's cash loan and
their credit card are two separate previous applications with their own
distinct `SK_ID_PREV`s - `pos_df` is already cash/POS loans only by
construction, and this filter can never remove anything from it.

100,458 of `pos_df`'s 337,252 customers (`SK_ID_CURR`) also appear in
`credit_card_balance.csv` - so if the goal is avoiding multicollinearity with
credit-card information, that overlap has to be handled at the `SK_ID_CURR`
level during feature engineering/merging (e.g. not double-counting the same
underlying credit behaviour once it's aggregated per customer), not by
filtering rows out of `pos_df` here.

So there does not seem to be that much information here. The suggestion is to move on to analysing another dataset.

# `previous_application.csv` Analysis

In [28]:
from column_analysis import print_all_tables

prev_app_df = pd.read_csv("home_credit/previous_application.csv")
credit_df = pd.read_csv("home_credit/credit_card_balance.csv")
instalments_df = pd.read_csv("home_credit/installments_payments.csv")
POS_balance_df = pd.read_csv("home_credit/POS_CASH_balance.csv")

In [4]:
from column_analysis import print_all_tables, basic_data_summary

basic_data_summary(prev_app_df)
print_all_tables(prev_app_df)

Shape: 1,670,214 rows x 37 columns
Memory: 1703.0 MB
Fully duplicated rows: 0

====================================================================================================
1. TYPE TABLE
====================================================================================================
                               dtype                inferred_type  n_unique  unique_ratio                   example  memory_mb
column
SK_ID_PREV                     int64         identifier (numeric)   1670214        1.0000                   2030495      12.74
SK_ID_CURR                     int64           numeric (discrete)    338857        0.2029                    271877      12.74
NAME_CONTRACT_TYPE               str                  categorical         4        0.0000            Consumer loans      97.68
AMT_ANNUITY                  float64         numeric (continuous)    357959        0.2143                   1730.43      12.74
AMT_APPLICATION              float64         numeric (continuous)     93885        0.0562                   17145.0      12.74
AMT_CREDIT                   float64         numeric (continuous)     86803        0.0520                   17145.0      12.74
AMT_DOWN_PAYMENT             float64         numeric (continuous)     29278        0.0175                       0.0      12.74
AMT_GOODS_PRICE              float64         numeric (continuous)     93885        0.0562                   17145.0      12.74
WEEKDAY_APPR_PROCESS_START       str                  categorical         7        0.0000                  SATURDAY      89.51
HOUR_APPR_PROCESS_START        int64  categorical (integer-coded)        24        0.0000                        15      12.74
FLAG_LAST_APPL_PER_CONTRACT      str                       binary         2        0.0000                         Y      79.64
NFLAG_LAST_APPL_IN_DAY         int64                       binary         2        0.0000                         1      12.74
RATE_DOWN_PAYMENT            float64         numeric (continuous)    207033        0.1240                       0.0      12.74
RATE_INTEREST_PRIMARY        float64         numeric (continuous)       148        0.0001        0.1828318032415278      12.74
RATE_INTEREST_PRIVILEGED     float64         numeric (continuous)        25        0.0000        0.8673361522198731      12.74
NAME_CASH_LOAN_PURPOSE           str                  categorical        25        0.0000                       XAP      83.33
NAME_CONTRACT_STATUS             str                  categorical         4        0.0000                  Approved      90.62
DAYS_DECISION                  int64           numeric (discrete)      2922        0.0017                       -73      12.74
NAME_PAYMENT_TYPE                str                  categorical         4        0.0000     Cash through the bank     100.79
CODE_REJECT_REASON               str                  categorical         9        0.0000                       XAP      82.88
NAME_TYPE_SUITE                  str                  categorical         7        0.0000             Unaccompanied      73.69
NAME_CLIENT_TYPE                 str                  categorical         4        0.0000                  Repeater      89.48
NAME_GOODS_CATEGORY              str                  categorical        28        0.0000                    Mobile      88.86
NAME_PORTFOLIO                   str                  categorical         5        0.0000                       POS      83.54
NAME_PRODUCT_TYPE                str                  categorical         3        0.0000                       XNA      84.71
CHANNEL_TYPE                     str                  categorical         8        0.0000              Country-wide     104.09
SELLERPLACE_AREA               int64           numeric (discrete)      2097        0.0013                        35      12.74
NAME_SELLER_INDUSTRY             str                  categorical        11        0.0000              Connectivity      92.53
CNT_PAYMENT                  float64  categorical (integer-coded)        49        0.0000                      12.0      12.74
NAME_YIELD_GROUP                 str                  categorical         5        0.0000                    middle      87.03
PRODUCT_COMBINATION              str                  categorical        17        0.0000  POS mobile with interest     107.05
DAYS_FIRST_DRAWING           float64           numeric (discrete)      2838        0.0017                  365243.0      12.74
DAYS_FIRST_DUE               float64           numeric (discrete)      2892        0.0017                     -42.0      12.74
DAYS_LAST_DUE_1ST_VERSION    float64           numeric (discrete)      4605        0.0028                     300.0      12.74
DAYS_LAST_DUE                float64           numeric (discrete)      2873        0.0017                     -42.0      12.74
DAYS_TERMINATION             float64           numeric (discrete)      2830        0.0017                     -37.0      12.74
NFLAG_INSURED_ON_APPROVAL    float64                       binary         2        0.0000                       0.0      12.74

====================================================================================================
2. MISSING VALUE TABLE
====================================================================================================
                             n_missing  pct_missing  n_native_nan  n_placeholder  n_present  complete
column
RATE_INTEREST_PRIVILEGED       1664263        99.64       1664263              0       5951     False
RATE_INTEREST_PRIMARY          1664263        99.64       1664263              0       5951     False
AMT_DOWN_PAYMENT                895844        53.64        895844              0     774370     False
RATE_DOWN_PAYMENT               895844        53.64        895844              0     774370     False
NAME_TYPE_SUITE                 820405        49.12        820405              0     849809     False
DAYS_TERMINATION                673065        40.30        673065              0     997149     False
DAYS_FIRST_DRAWING              673065        40.30        673065              0     997149     False
DAYS_FIRST_DUE                  673065        40.30        673065              0     997149     False
DAYS_LAST_DUE_1ST_VERSION       673065        40.30        673065              0     997149     False
DAYS_LAST_DUE                   673065        40.30        673065              0     997149     False
NFLAG_INSURED_ON_APPROVAL       673065        40.30        673065              0     997149     False
AMT_GOODS_PRICE                 385515        23.08        385515              0    1284699     False
AMT_ANNUITY                     372235        22.29        372235              0    1297979     False
CNT_PAYMENT                     372230        22.29        372230              0    1297984     False
PRODUCT_COMBINATION                346         0.02           346              0    1669868     False
SK_ID_CURR                           0         0.00             0              0    1670214      True
SK_ID_PREV                           0         0.00             0              0    1670214      True
AMT_APPLICATION                      0         0.00             0              0    1670214      True
NAME_CONTRACT_TYPE                   0         0.00             0              0    1670214      True
WEEKDAY_APPR_PROCESS_START           0         0.00             0              0    1670214      True
AMT_CREDIT                           1         0.00             1              0    1670213     False
CODE_REJECT_REASON                   0         0.00             0              0    1670214      True
NAME_PAYMENT_TYPE                    0         0.00             0              0    1670214      True
DAYS_DECISION                        0         0.00             0              0    1670214      True
NAME_CONTRACT_STATUS                 0         0.00             0              0    1670214      True
NAME_CASH_LOAN_PURPOSE               0         0.00             0              0    1670214      True
HOUR_APPR_PROCESS_START              0         0.00             0              0    1670214      True
FLAG_LAST_APPL_PER_CONTRACT          0         0.00             0              0    1670214      True
NFLAG_LAST_APPL_IN_DAY               0         0.00             0              0    1670214      True
NAME_SELLER_INDUSTRY                 0         0.00             0              0    1670214      True
SELLERPLACE_AREA                     0         0.00             0              0    1670214      True
CHANNEL_TYPE                         0         0.00             0              0    1670214      True
NAME_PRODUCT_TYPE                    0         0.00             0              0    1670214      True
NAME_GOODS_CATEGORY                  0         0.00             0              0    1670214      True
NAME_PORTFOLIO                       0         0.00             0              0    1670214      True
NAME_CLIENT_TYPE                     0         0.00             0              0    1670214      True
NAME_YIELD_GROUP                     0         0.00             0              0    1670214      True

====================================================================================================
3a. NUMERICAL SUMMARY TABLE
====================================================================================================
                               count          mean            std           min           25%           50%           75%          max
column
SK_ID_PREV                 1670214.0  1.923089e+06  532597.958696  1.000001e+06  1.461857e+06  1.923110e+06  2.384280e+06  2845382.000
SK_ID_CURR                 1670214.0  2.783572e+05  102814.823849  1.000010e+05  1.893290e+05  2.787145e+05  3.675140e+05   456255.000
AMT_ANNUITY                1297979.0  1.595512e+04   14782.137335  0.000000e+00  6.321780e+03  1.125000e+04  2.065842e+04   418058.145
AMT_APPLICATION            1670214.0  1.752339e+05  292779.762386  0.000000e+00  1.872000e+04  7.104600e+04  1.803600e+05  6905160.000
AMT_CREDIT                 1670213.0  1.961140e+05  318574.616547  0.000000e+00  2.416050e+04  8.054100e+04  2.164185e+05  6905160.000
AMT_DOWN_PAYMENT            774370.0  6.697402e+03   20921.495410 -9.000000e-01  0.000000e+00  1.638000e+03  7.740000e+03  3060045.000
AMT_GOODS_PRICE            1284699.0  2.278473e+05  315396.557937  0.000000e+00  5.084100e+04  1.123200e+05  2.340000e+05  6905160.000
RATE_DOWN_PAYMENT           774370.0  7.963682e-02       0.107823 -1.497876e-05  0.000000e+00  5.160508e-02  1.089091e-01        1.000
RATE_INTEREST_PRIMARY         5951.0  1.883569e-01       0.087671  3.478125e-02  1.607163e-01  1.891222e-01  1.933299e-01        1.000
RATE_INTEREST_PRIVILEGED      5951.0  7.735025e-01       0.100879  3.731501e-01  7.156448e-01  8.350951e-01  8.525370e-01        1.000
DAYS_DECISION              1670214.0 -8.806797e+02     779.099667 -2.922000e+03 -1.300000e+03 -5.810000e+02 -2.800000e+02       -1.000
SELLERPLACE_AREA           1670214.0  3.139511e+02    7127.443459 -1.000000e+00 -1.000000e+00  3.000000e+00  8.200000e+01  4000000.000
DAYS_FIRST_DRAWING          997149.0  3.422099e+05   88916.115833 -2.922000e+03  3.652430e+05  3.652430e+05  3.652430e+05   365243.000
DAYS_FIRST_DUE              997149.0  1.382627e+04   72444.869708 -2.892000e+03 -1.628000e+03 -8.310000e+02 -4.110000e+02   365243.000
DAYS_LAST_DUE_1ST_VERSION   997149.0  3.376777e+04  106857.034789 -2.801000e+03 -1.242000e+03 -3.610000e+02  1.290000e+02   365243.000
DAYS_LAST_DUE               997149.0  7.658240e+04  149647.415123 -2.889000e+03 -1.314000e+03 -5.370000e+02 -7.400000e+01   365243.000
DAYS_TERMINATION            997149.0  8.199234e+04  153303.516729 -2.874000e+03 -1.270000e+03 -4.990000e+02 -4.400000e+01   365243.000

====================================================================================================
3b. CATEGORICAL SUMMARY TABLE
====================================================================================================
                               count  n_unique                    top_1                        top_2                       top_3                                      top_4             top_5
column
NAME_CONTRACT_TYPE           1670214         4               Cash loans               Consumer loans             Revolving loans                                        XNA               NaN
WEEKDAY_APPR_PROCESS_START   1670214         7                  TUESDAY                    WEDNESDAY                      MONDAY                                     FRIDAY          THURSDAY
HOUR_APPR_PROCESS_START      1670214        24                       11                           12                          10                                         13                14
FLAG_LAST_APPL_PER_CONTRACT  1670214         2                        Y                            N                         NaN                                        NaN               NaN
NFLAG_LAST_APPL_IN_DAY       1670214         2                        1                            0                         NaN                                        NaN               NaN
NAME_CASH_LOAN_PURPOSE       1670214        25                      XAP                          XNA                     Repairs                                      Other      Urgent needs
NAME_CONTRACT_STATUS         1670214         4                 Approved                     Canceled                     Refused                               Unused offer               NaN
NAME_PAYMENT_TYPE            1670214         4    Cash through the bank                          XNA  Non-cash from your account  Cashless from the account of the employer               NaN
CODE_REJECT_REASON           1670214         9                      XAP                           HC                       LIMIT                                        SCO            CLIENT
NAME_TYPE_SUITE               849809         8                      NaN                Unaccompanied                      Family                            Spouse, partner          Children
NAME_CLIENT_TYPE             1670214         4                 Repeater                          New                   Refreshed                                        XNA               NaN
NAME_GOODS_CATEGORY          1670214        28                      XNA                       Mobile        Consumer Electronics                                  Computers       Audio/Video
NAME_PORTFOLIO               1670214         5                      POS                         Cash                         XNA                                      Cards              Cars
NAME_PRODUCT_TYPE            1670214         3                      XNA                       x-sell                     walk-in                                        NaN               NaN
CHANNEL_TYPE                 1670214         8  Credit and cash offices                 Country-wide                       Stone                           Regional / Local    Contact center
NAME_SELLER_INDUSTRY         1670214        11                      XNA         Consumer electronics                Connectivity                                  Furniture      Construction
CNT_PAYMENT                  1297984        50                      NaN                         12.0                         6.0                                        0.0              10.0
NAME_YIELD_GROUP             1670214         5                      XNA                       middle                        high                                 low_normal        low_action
PRODUCT_COMBINATION          1669868        18                     Cash  POS household with interest    POS mobile with interest                        Cash X-Sell: middle  Cash X-Sell: low
NFLAG_INSURED_ON_APPROVAL     997149         3                      NaN                          0.0                         1.0                                        NaN               NaN

In [8]:
from column_analysis import print_all_tables, basic_data_summary

basic_data_summary(credit_df)
print_all_tables(credit_df)

Shape: 3,840,312 rows x 23 columns
Memory: 846.4 MB
Fully duplicated rows: 0

====================================================================================================
1. TYPE TABLE
====================================================================================================
                              dtype                inferred_type  n_unique  unique_ratio   example  memory_mb
column
SK_ID_PREV                    int64           numeric (discrete)    104307        0.0272   2562384       29.3
SK_ID_CURR                    int64           numeric (discrete)    103558        0.0270    378907       29.3
MONTHS_BALANCE                int64           numeric (discrete)        96        0.0000        -6       29.3
AMT_BALANCE                 float64         numeric (continuous)   1347904        0.3510     56.97       29.3
AMT_CREDIT_LIMIT_ACTUAL       int64           numeric (discrete)       181        0.0000    135000       29.3
AMT_DRAWINGS_ATM_CURRENT    float64         numeric (continuous)      2267        0.0006       0.0       29.3
AMT_DRAWINGS_CURRENT        float64         numeric (continuous)    187005        0.0487     877.5       29.3
AMT_DRAWINGS_OTHER_CURRENT  float64         numeric (continuous)      1832        0.0005       0.0       29.3
AMT_DRAWINGS_POS_CURRENT    float64         numeric (continuous)    168748        0.0439     877.5       29.3
AMT_INST_MIN_REGULARITY     float64         numeric (continuous)    312266        0.0813  1700.325       29.3
AMT_PAYMENT_CURRENT         float64         numeric (continuous)    163209        0.0425    1800.0       29.3
AMT_PAYMENT_TOTAL_CURRENT   float64         numeric (continuous)    182957        0.0476    1800.0       29.3
AMT_RECEIVABLE_PRINCIPAL    float64         numeric (continuous)   1195839        0.3114       0.0       29.3
AMT_RECIVABLE               float64         numeric (continuous)   1338878        0.3486       0.0       29.3
AMT_TOTAL_RECEIVABLE        float64         numeric (continuous)   1339008        0.3487       0.0       29.3
CNT_DRAWINGS_ATM_CURRENT    float64  categorical (integer-coded)        44        0.0000       0.0       29.3
CNT_DRAWINGS_CURRENT          int64           numeric (discrete)       129        0.0000         1       29.3
CNT_DRAWINGS_OTHER_CURRENT  float64  categorical (integer-coded)        11        0.0000       0.0       29.3
CNT_DRAWINGS_POS_CURRENT    float64           numeric (discrete)       133        0.0000       1.0       29.3
CNT_INSTALMENT_MATURE_CUM   float64           numeric (discrete)       121        0.0000      35.0       29.3
NAME_CONTRACT_STATUS            str                  categorical         7        0.0000    Active      201.8
SK_DPD                        int64           numeric (discrete)       917        0.0002         0       29.3
SK_DPD_DEF                    int64           numeric (discrete)       378        0.0001         0       29.3

====================================================================================================
2. MISSING VALUE TABLE
====================================================================================================
                            n_missing  pct_missing  n_native_nan  n_placeholder  n_present  complete
column
AMT_PAYMENT_CURRENT            767988        20.00        767988              0    3072324     False
CNT_DRAWINGS_POS_CURRENT       749816        19.52        749816              0    3090496     False
AMT_DRAWINGS_ATM_CURRENT       749816        19.52        749816              0    3090496     False
CNT_DRAWINGS_ATM_CURRENT       749816        19.52        749816              0    3090496     False
AMT_DRAWINGS_POS_CURRENT       749816        19.52        749816              0    3090496     False
AMT_DRAWINGS_OTHER_CURRENT     749816        19.52        749816              0    3090496     False
CNT_DRAWINGS_OTHER_CURRENT     749816        19.52        749816              0    3090496     False
CNT_INSTALMENT_MATURE_CUM      305236         7.95        305236              0    3535076     False
AMT_INST_MIN_REGULARITY        305236         7.95        305236              0    3535076     False
AMT_DRAWINGS_CURRENT                0         0.00             0              0    3840312      True
AMT_CREDIT_LIMIT_ACTUAL             0         0.00             0              0    3840312      True
SK_ID_PREV                          0         0.00             0              0    3840312      True
SK_ID_CURR                          0         0.00             0              0    3840312      True
AMT_BALANCE                         0         0.00             0              0    3840312      True
MONTHS_BALANCE                      0         0.00             0              0    3840312      True
AMT_TOTAL_RECEIVABLE                0         0.00             0              0    3840312      True
AMT_RECIVABLE                       0         0.00             0              0    3840312      True
AMT_RECEIVABLE_PRINCIPAL            0         0.00             0              0    3840312      True
AMT_PAYMENT_TOTAL_CURRENT           0         0.00             0              0    3840312      True
CNT_DRAWINGS_CURRENT                0         0.00             0              0    3840312      True
NAME_CONTRACT_STATUS                0         0.00             0              0    3840312      True
SK_DPD                              0         0.00             0              0    3840312      True
SK_DPD_DEF                          0         0.00             0              0    3840312      True

====================================================================================================
3a. NUMERICAL SUMMARY TABLE
====================================================================================================
                                count          mean            std          min         25%        50%           75%          max
column
SK_ID_PREV                  3840312.0  1.904504e+06  536469.470563  1000018.000  1434385.00  1897122.0  2.369328e+06  2843496.000
SK_ID_CURR                  3840312.0  2.783242e+05  102704.475133   100006.000   189517.00   278396.0  3.675800e+05   456250.000
MONTHS_BALANCE              3840312.0 -3.452192e+01      26.667751      -96.000      -55.00      -28.0 -1.100000e+01       -1.000
AMT_BALANCE                 3840312.0  5.830016e+04  106307.031024  -420250.185        0.00        0.0  8.904669e+04  1505902.185
AMT_CREDIT_LIMIT_ACTUAL     3840312.0  1.538080e+05  165145.699525        0.000    45000.00   112500.0  1.800000e+05  1350000.000
AMT_DRAWINGS_ATM_CURRENT    3090496.0  5.961325e+03   28225.688578    -6827.310        0.00        0.0  0.000000e+00  2115000.000
AMT_DRAWINGS_CURRENT        3840312.0  7.433388e+03   33846.077333    -6211.620        0.00        0.0  0.000000e+00  2287098.315
AMT_DRAWINGS_OTHER_CURRENT  3090496.0  2.881696e+02    8201.989345        0.000        0.00        0.0  0.000000e+00  1529847.000
AMT_DRAWINGS_POS_CURRENT    3090496.0  2.968805e+03   20796.887047        0.000        0.00        0.0  0.000000e+00  2239274.160
AMT_INST_MIN_REGULARITY     3535076.0  3.540204e+03    5600.154122        0.000        0.00        0.0  6.633911e+03   202882.005
AMT_PAYMENT_CURRENT         3072324.0  1.028054e+04   36078.084953        0.000      152.37     2702.7  9.000000e+03  4289207.445
AMT_PAYMENT_TOTAL_CURRENT   3840312.0  7.588857e+03   32005.987768        0.000        0.00        0.0  6.750000e+03  4278315.690
AMT_RECEIVABLE_PRINCIPAL    3840312.0  5.596588e+04  102533.616846  -423305.820        0.00        0.0  8.535924e+04  1472316.795
AMT_RECIVABLE               3840312.0  5.808881e+04  105965.369908  -420250.185        0.00        0.0  8.889949e+04  1493338.185
AMT_TOTAL_RECEIVABLE        3840312.0  5.809829e+04  105971.801104  -420250.185        0.00        0.0  8.891451e+04  1493338.185
CNT_DRAWINGS_CURRENT        3840312.0  7.031439e-01       3.190347        0.000        0.00        0.0  0.000000e+00      165.000
CNT_DRAWINGS_POS_CURRENT    3090496.0  5.594791e-01       3.240649        0.000        0.00        0.0  0.000000e+00      165.000
CNT_INSTALMENT_MATURE_CUM   3535076.0  2.082508e+01      20.051494        0.000        4.00       15.0  3.200000e+01      120.000
SK_DPD                      3840312.0  9.283667e+00      97.515700        0.000        0.00        0.0  0.000000e+00     3260.000
SK_DPD_DEF                  3840312.0  3.316220e-01      21.479231        0.000        0.00        0.0  0.000000e+00     3260.000

====================================================================================================
3b. CATEGORICAL SUMMARY TABLE
====================================================================================================
                              count  n_unique   top_1      top_2   top_3   top_4          top_5
column
CNT_DRAWINGS_ATM_CURRENT    3090496        45     0.0        NaN     1.0     2.0            3.0
CNT_DRAWINGS_OTHER_CURRENT  3090496        12     0.0        NaN     1.0     2.0            3.0
NAME_CONTRACT_STATUS        3840312         7  Active  Completed  Signed  Demand  Sent proposal

In [10]:
from column_analysis import print_all_tables, basic_data_summary

basic_data_summary(instalments_df)
print_all_tables(instalments_df)

Shape: 13,605,401 rows x 8 columns
Memory: 830.4 MB
Fully duplicated rows: 0

====================================================================================================
1. TYPE TABLE
====================================================================================================
                          dtype         inferred_type  n_unique  unique_ratio  example  memory_mb
column
SK_ID_PREV                int64    numeric (discrete)    997752        0.0733  1054186      103.8
SK_ID_CURR                int64    numeric (discrete)    339587        0.0250   161674      103.8
NUM_INSTALMENT_VERSION  float64    numeric (discrete)        65        0.0000      1.0      103.8
NUM_INSTALMENT_NUMBER     int64    numeric (discrete)       277        0.0000        6      103.8
DAYS_INSTALMENT         float64    numeric (discrete)      2922        0.0002  -1180.0      103.8
DAYS_ENTRY_PAYMENT      float64    numeric (discrete)      3039        0.0002  -1187.0      103.8
AMT_INSTALMENT          float64  numeric (continuous)    902539        0.0663  6948.36      103.8
AMT_PAYMENT             float64  numeric (continuous)    944235        0.0694  6948.36      103.8

====================================================================================================
2. MISSING VALUE TABLE
====================================================================================================
                        n_missing  pct_missing  n_native_nan  n_placeholder  n_present  complete
column
AMT_PAYMENT                  2905         0.02          2905              0   13602496     False
DAYS_ENTRY_PAYMENT           2905         0.02          2905              0   13602496     False
SK_ID_PREV                      0         0.00             0              0   13605401      True
SK_ID_CURR                      0         0.00             0              0   13605401      True
NUM_INSTALMENT_NUMBER           0         0.00             0              0   13605401      True
NUM_INSTALMENT_VERSION          0         0.00             0              0   13605401      True
DAYS_INSTALMENT                 0         0.00             0              0   13605401      True
AMT_INSTALMENT                  0         0.00             0              0   13605401      True

====================================================================================================
3a. NUMERICAL SUMMARY TABLE
====================================================================================================
                             count          mean            std        min          25%          50%          75%          max
column
SK_ID_PREV              13605401.0  1.903365e+06  536202.905546  1000001.0  1434191.000  1896520.000  2369094.000  2843499.000
SK_ID_CURR              13605401.0  2.784449e+05  102718.310411   100001.0   189639.000   278685.000   367530.000   456255.000
NUM_INSTALMENT_VERSION  13605401.0  8.566373e-01       1.035216        0.0        0.000        1.000        1.000      178.000
NUM_INSTALMENT_NUMBER   13605401.0  1.887090e+01      26.664067        1.0        4.000        8.000       19.000      277.000
DAYS_INSTALMENT         13605401.0 -1.042270e+03     800.946284    -2922.0    -1654.000     -818.000     -361.000       -1.000
DAYS_ENTRY_PAYMENT      13602496.0 -1.051114e+03     800.585883    -4921.0    -1662.000     -827.000     -370.000       -1.000
AMT_INSTALMENT          13605401.0  1.705091e+04   50570.254429        0.0     4226.085     8884.080    16710.210  3771487.845
AMT_PAYMENT             13602496.0  1.723822e+04   54735.783981        0.0     3398.265     8125.515    16108.425  3771487.845

====================================================================================================
3b. CATEGORICAL SUMMARY TABLE
====================================================================================================

KeyError: "None of ['column'] are in the columns"

In [29]:
from column_analysis import print_all_tables

basic_data_summary(POS_balance_df)
print_all_tables(POS_balance_df)

Shape: 10,001,358 rows x 8 columns
Memory: 1060.9 MB
Fully duplicated rows: 0

====================================================================================================
1. TYPE TABLE
====================================================================================================
                         dtype       inferred_type  n_unique  unique_ratio  example  memory_mb
column
SK_ID_PREV               int64  numeric (discrete)    936325        0.0936  1803195      76.30
SK_ID_CURR               int64  numeric (discrete)    337252        0.0337   182943      76.30
MONTHS_BALANCE           int64  numeric (discrete)        96        0.0000      -31      76.30
CNT_INSTALMENT         float64  numeric (discrete)        73        0.0000     48.0      76.30
CNT_INSTALMENT_FUTURE  float64  numeric (discrete)        79        0.0000     45.0      76.30
NAME_CONTRACT_STATUS       str         categorical         9        0.0000   Active     526.82
SK_DPD                   int64  numeric (discrete)      3400        0.0003        0      76.30
SK_DPD_DEF               int64  numeric (discrete)      2307        0.0002        0      76.30

====================================================================================================
2. MISSING VALUE TABLE
====================================================================================================
                       n_missing  pct_missing  n_native_nan  n_placeholder  n_present  complete
column
CNT_INSTALMENT             26071         0.26         26071              0    9975287     False
CNT_INSTALMENT_FUTURE      26087         0.26         26087              0    9975271     False
SK_ID_CURR                     0         0.00             0              0   10001358      True
SK_ID_PREV                     0         0.00             0              0   10001358      True
MONTHS_BALANCE                 0         0.00             0              0   10001358      True
NAME_CONTRACT_STATUS           0         0.00             0              0   10001358      True
SK_DPD                         0         0.00             0              0   10001358      True
SK_DPD_DEF                     0         0.00             0              0   10001358      True

====================================================================================================
3a. NUMERICAL SUMMARY TABLE
====================================================================================================
                            count          mean            std        min        25%        50%        75%        max
column
SK_ID_PREV             10001358.0  1.903217e+06  535846.530722  1000001.0  1434405.0  1896565.0  2368963.0  2843499.0
SK_ID_CURR             10001358.0  2.784039e+05  102763.745090   100001.0   189550.0   278654.0   367429.0   456255.0
MONTHS_BALANCE         10001358.0 -3.501259e+01      26.066570      -96.0      -54.0      -28.0      -13.0       -1.0
CNT_INSTALMENT          9975287.0  1.708965e+01      11.995056        1.0       10.0       12.0       24.0       92.0
CNT_INSTALMENT_FUTURE   9975271.0  1.048384e+01      11.109058        0.0        3.0        7.0       14.0       85.0
SK_DPD                 10001358.0  1.160693e+01     132.714043        0.0        0.0        0.0        0.0     4231.0
SK_DPD_DEF             10001358.0  6.544684e-01      32.762491        0.0        0.0        0.0        0.0     3595.0

====================================================================================================
3b. CATEGORICAL SUMMARY TABLE
====================================================================================================
                         count  n_unique   top_1      top_2   top_3   top_4                  top_5
column
NAME_CONTRACT_STATUS  10001358         9  Active  Completed  Signed  Demand  Returned to the store

The goal now is to perform a more detailed analysis on some column that accounts only for consumer and cash loans. This will be done by only filtering the entries which have ids that are not already in the credit card dataset.

In [ ]:
non_credit_entries = ~(prev_app_df.SK_ID_PREV.isin(credit_df.SK_ID_PREV))
print("Are there less entries in prev_app_df after removing credit_data?", {non_credit_entries.sum() < len(prev_app_df)})
print(prev_app_df[non_credit_entries]["NAME_CONTRACT_TYPE"].value_counts().to_string())

Are there less entries in prev_app_df after removing credit_data? {np.True_}
NAME_CONTRACT_TYPE
Cash loans         747553
Consumer loans     729151
Revolving loans    100229
XNA                   346

After analysing, we learn that "XNA" actually stands for the category  "Missing" in financial datasets. To handle this entry therefore and homogeneity with the rest of the dataframe, we will replace "XNA" with the word "Missing". Furthermore noting that XNA only occupies a small part of the `NAME_CONTRACT_TYPE` that we are interested in, it's worth dropping these entries (even if they contain loans that might potentially be defaulting.)

In [15]:
prev_app_clean = prev_app_df[~(prev_app_df["NAME_CONTRACT_TYPE"] == "XNA")]

We now want to obtain information about the previous payment history for the cash loans that we have filtered out. We will do that by filtering out the rows in `installments_payments.csv` that have overlapping ids with `previous_application.csv`. 

Furthermore, we would also like to restrict our attention to loans that have been paid off in the last 12 months only. This will be done in the `installments_payments.csv` dataset. 

We would then like to obtain information on the latest amount paid on each loan, particularly on the loans that are currently active. 

1. We need to filter out loans that are currently active. 
2. We need to then search for the latest amount paid on these loans

We would then like to sum up the total of these loans to get a rough idea on how much instalments the consumer is paying on previous credit within the bank.

In [17]:
# Restrict installments_payments.csv to loans that also appear in
# prev_app_df (previous_application.csv) - excludes the ~4% of installment
# rows whose SK_ID_PREV has no matching previous-application record.
instalments_matched = instalments_df[instalments_df["SK_ID_PREV"].isin(prev_app_df["SK_ID_PREV"])]

print(f"instalments_df rows before: {len(instalments_df):,}")
print(f"instalments_matched rows after: {len(instalments_matched):,}")

# For each loan, the latest installment is the one with the largest
# (least negative) DAYS_INSTALMENT - the due date closest to the
# application date.
latest_instalment_idx = instalments_matched.groupby("SK_ID_PREV")["DAYS_INSTALMENT"].idxmax()

latest_instalments = instalments_matched.loc[
    latest_instalment_idx, ["SK_ID_PREV", "SK_ID_CURR", "AMT_PAYMENT", "AMT_INSTALMENT", "DAYS_INSTALMENT"]
].rename(columns={"AMT_PAYMENT": "LATEST_AMT_PAID", "AMT_INSTALMENT": "LATEST_AMT_INSTALMENT"})

# DAYS_INSTALMENT is negative (days before application) - flip sign so
# "days ago" reads as a positive distance into the past.
latest_instalments["DAYS_AGO_DUE"] = latest_instalments["DAYS_INSTALMENT"]
latest_instalments = latest_instalments.drop(columns=["DAYS_INSTALMENT"]).set_index("SK_ID_PREV")

latest_instalments.describe()

instalments_df rows before: 13,605,401
instalments_matched rows after: 12,354,575

          SK_ID_CURR  LATEST_AMT_PAID  LATEST_AMT_INSTALMENT   DAYS_AGO_DUE
count  958905.000000     9.577600e+05           9.589050e+05  958905.000000
mean   278306.493054     6.105225e+04           6.123719e+04    -802.945214
std    102782.362219     1.568267e+05           1.566219e+05     778.077959
min    100001.000000     0.000000e+00           0.000000e+00   -2889.000000
25%    189363.000000     6.838864e+03           7.222140e+03   -1331.000000
50%    278489.000000     1.440000e+04           1.470857e+04    -555.000000
75%    367376.000000     3.794016e+04           3.796636e+04    -104.000000
max    456255.000000     3.771488e+06           3.771488e+06      -1.000000

In [27]:
instalments_matched[(instalments_matched["DAYS_ENTRY_PAYMENT"] > -365) & (instalments_matched["AMT_PAYMENT"] == 0)]

,SK_ID_PREV,SK_ID_CURR,NUM_INSTALMENT_VERSION,NUM_INSTALMENT_NUMBER,DAYS_INSTALMENT,DAYS_ENTRY_PAYMENT,AMT_INSTALMENT,AMT_PAYMENT
3945254,2198450,242609,4.0,13,-291.0,-291.0,0.0,0.0
4021596,2028864,289626,2.0,3,-29.0,-28.0,0.0,0.0

In [ ]:
# Loans active in the current month: MONTHS_BALANCE == -1 (the most recent
# observed month, relative to application - POS_CASH_balance.csv never has
# a positive MONTHS_BALANCE) and NAME_CONTRACT_STATUS == "Active".
pos_active_current = POS_balance_df[
    (POS_balance_df["MONTHS_BALANCE"] == -1) & (POS_balance_df["NAME_CONTRACT_STATUS"] == "Active")
]

print(f"POS_balance_df rows: {len(POS_balance_df):,}")
print(f"pos_active_current rows (loans): {len(pos_active_current):,}")

# Same latest_instalments construction as above, restricted to these
# currently-active loans instead of every loan in prev_app_df.
instalments_active_current = instalments_matched[
    instalments_matched["SK_ID_PREV"].isin(pos_active_current["SK_ID_PREV"])
]

latest_instalment_idx_active = instalments_active_current.groupby("SK_ID_PREV")["DAYS_INSTALMENT"].idxmax()

latest_instalments_active = instalments_active_current.loc[
    latest_instalment_idx_active, ["SK_ID_PREV", "SK_ID_CURR", "AMT_PAYMENT", "AMT_INSTALMENT", "DAYS_INSTALMENT"]
].rename(columns={"AMT_PAYMENT": "LATEST_AMT_PAID", "AMT_INSTALMENT": "LATEST_AMT_INSTALMENT"})
latest_instalments_active["DAYS_AGO_DUE"] = latest_instalments_active["DAYS_INSTALMENT"]
latest_instalments_active = latest_instalments_active.drop(columns=["DAYS_INSTALMENT"]).set_index("SK_ID_PREV")

print(f"latest_instalments_active rows (loans matched to an installment record): {len(latest_instalments_active):,}")
latest_instalments_active.describe()

In [ ]:
# Per customer, sum the latest installment amount paid across all of their
# currently-active loans - a rough measure of how much a customer is
# currently paying toward previous credit within the bank.
customer_active_instalment_paid = (
    latest_instalments_active.groupby("SK_ID_CURR")["LATEST_AMT_PAID"].sum()
    .rename("SUM_LATEST_AMT_PAID_ACTIVE")
)

print(f"customers with at least one currently-active loan: {len(customer_active_instalment_paid):,}")
customer_active_instalment_paid.describe()

**Known wrong assumption in `SUM_LATEST_AMT_PAID_ACTIVE`**: for a customer with
more than one currently-active loan, this sums each loan's own most recent
`LATEST_AMT_PAID` - but each loan's "most recent" installment is found
independently, so for a multi-loan customer these payments are **not**
guaranteed to fall in the same month. Summing them together therefore isn't a
"total paid this month" figure; it's closer to "sum of whichever payment
happened to be each loan's latest one," which can span very different dates.

Verified against the data: of 10,691 customers with more than one
currently-active loan in this table, 10,414 (97.4%) have loans whose latest
`DAYS_AGO_DUE` values differ from each other - median gap ~10 days, max gap
2,555 days. So this is a real, common case here, not a rare edge case.

This is a known-wrong simplification, kept deliberately for now to get a
first version of the feature working quickly - revisit by aligning to a
shared month (e.g. summing each loan's payment within the same
`MONTHS_BALANCE` window) before relying on this for anything beyond a rough
first pass.